maintainer: Mert Cobanov

pca-params:
  n-components: 224

umap-params:
  min_dist:
    - 0.01
    - 0.1
    - 0.5
  spread: 1.0
  metrics:
    - euclidean
    - l1
    - manhattan
    - chebyshev

visualiz-params:
  median-threshold: 6
